version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./db:/root/db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./db:/db

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - ./db:/app/db